ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB*
#ARDUINO_PORT = /dev/ttyACM*

#USER_LIB_PATH = /home/radek/ardu/libraries/

BOARD_TAG = nano328
#BOARD_TAG = uno
#BOARD_TAG = atmega328

include /usr/share/arduino/Arduino.mk
